Petz.Web/Pages/App/Pets/AddPet.cshtml.cs
using System.IO;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Configuration;

using Petz.Dal.Entities;
using Petz.Dal.Services;

namespace Petz.Web.Pages.App
{
    [Authorize]
    public class AddPetModel : PageModel
    {
        private readonly ILogger<AddPetModel> _logger;
        private readonly IWebHostEnvironment _environment;
        private readonly long _fileSizeLimit;
        private List<string> _allowedImageExtensions;

        [BindProperty(SupportsGet = true)]
        public int Id { get; set; }

        [BindProperty]
        public Family Family { get; set; }

        [BindProperty]
        public PetInputModel PetInput { get; set; }

        [BindProperty]
        public IFormFile PetImage { get; set; }

        public enum Animal {
            Dog,
            Cat,
            Fish,
            Hamster    
        }
        
        public class PetInputModel
        {
            [Required]
            public string Name { get; set; }

            [Required]
            public Animal Type { get; set; }

            public string Breed { get; set; }
        }

        public AddPetModel(ILogger<AddPetModel> logger, IConfiguration configuration, IWebHostEnvironment environment)
        {
            _logger = logger;
            _environment = environment;
            _fileSizeLimit = configuration.GetValue<long>("FileSizeLimit");
            _allowedImageExtensions = configuration.GetSection("AllowedImageExtensions").Get<List<string>>();
        }

        public void OnGet([FromServices] FamilyService familyService)
        {
            Family = familyService.GetFamilyById(Id); 
        }

        public async Task<IActionResult> OnPostAsync([FromServices] FamilyService familyService) 
        {
            if(ModelState.IsValid)
            {
                var fileName = PetImage.FileName;
                var extension = Path.GetExtension(fileName).ToLowerInvariant();

                if(string.IsNullOrEmpty(extension) || !_allowedImageExtensions.Contains(extension))
                {
                    ModelState.AddModelError("PetImage", "The uploaded image is not of proper extension.");
                    return Page();
                }

                Family = familyService.GetFamilyById(Id); 

                Pet pet = new Pet
                {
                    Name = PetInput.Name,
                    Type = (Petz.Dal.Entities.Animal) PetInput.Type,
                    Breed = PetInput.Breed
                };

                var petId = await familyService.AddPetToFamilyAsync(Id, pet);

                if(PetImage != null)
                {
                    var filePath = Path.Combine(_environment.WebRootPath, $"img/pets/{petId}{extension}");
                    using(var stream = System.IO.File.Create(filePath))
                    {
                        await PetImage.CopyToAsync(stream);
                    }
                }
                
                return LocalRedirect("~/App/Families/Family?id=" + Id);
            }

            return Page();
        }
    }
}

Petz.Web/Pages/App/Pets/Pet.cshtml.cs
using System.Threading.Tasks;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication;
using Microsoft.Extensions.Logging;

using Petz.Dal.Dtos;
using Petz.Dal.Entities;
using Petz.Dal.Services;

namespace Petz.Web.Pages.App.Pets
{
    [Authorize]
    public class PetModel : PageModel
    {
        private readonly ILogger<PetModel> _logger;

        [BindProperty(SupportsGet = true)]
        public int Id { get; set; }

        [BindProperty]
        public int TaskId { get; set; }

        public Pet Pet { get; set; }
        public List<PetTask> UncompletedTasks { get; set; }

        public PetModel(ILogger<PetModel> logger)
        {
            _logger = logger;
        }

        public void OnGet([FromServices] PetService petService)
        {
            Pet = petService.GetPetById(Id);
            UncompletedTasks = Pet.PetTasks.Where(task => task.Status != PetTaskStatus.Done).ToList();
        }

        public async Task<IActionResult> OnPostCompleteAsync([FromServices] PetService petService, [FromServices] RecordService recordService)
        {
            Pet = petService.GetPetById(Id);

            await recordService.CompleteTaskByIdAsync(TaskId);
            return LocalRedirect("~/App/Pets/Pet?id=" + Pet.Id);
        }
    }
}

Petz.Web/Pages/App/Pets/RemovePet.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication;
using Microsoft.Extensions.Logging;

using Petz.Dal.Dtos;
using Petz.Dal.Entities;
using Petz.Dal.Services;


namespace Petz.Web.Pages.App.Pets
{
    [Authorize]
    public class RemovePetModel : PageModel
    {
        private readonly ILogger<RemovePetModel> _logger;

        [BindProperty(SupportsGet = true)]
        public int Id { get; set; }

        public Pet CurrentPet { get; set; }

        public RemovePetModel(ILogger<RemovePetModel> logger)
        {
            _logger = logger;
        }

        public void OnGet([FromServices] PetService petService)
        {
            CurrentPet = petService.GetPetById(Id);
        }

        public async Task<IActionResult> OnPostAsync([FromServices] PetService petService)
        {
            CurrentPet = petService.GetPetById(Id);
            
            await petService.RemovePetByIdAsync(Id);
            return LocalRedirect("~/App/Families/Family?id=" + CurrentPet.Family.Id);
        }
    }
}

Petz.Web/Pages/App/Pets/AddPet.cshtml
@page
@model AddPetModel
@{
    ViewData["Title"] = "Add pet";
}


<div class="font-sans min-h-screen flex items-start justify-center py-12 px-4 sm:px-6 lg:px-8">
  <div class="max-w-md w-full space-y-8">
    <div>
      <img class="mx-auto h-12 w-auto" src="/img/logo.png" alt="Petz">
      <h2 class="mt-6 text-center text-3xl font-extrabold text-gray-900">Add a pet to the <span class="text-indigo-500">@Model.Family.Name</span> family</h2>
    </div>
    <section>
      <form method="post" class="mt-8 space-y-6" enctype="multipart/form-data" role="form">
        <div class="form-group">
            <input asp-for="PetInput.Name" class="form-control rounded-md appearance-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10" placeholder="Name" />
            <span asp-validation-for="PetInput.Name" class="block text-sm ml-2 text-gray-900"></span>
        </div>
        <div class="form-group">
            <select asp-for="PetInput.Type" asp-items="Html.GetEnumSelectList<AddPetModel.Animal>()" class="form-control rounded-md appearance-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10"></select>
            <span asp-validation-for="PetInput.Type" class="block text-sm ml-2 text-gray-900"></span>
        </div>
        <div class="form-group">
            <input asp-for="PetInput.Breed" class="form-control rounded-md appearance-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10" placeholder="Breed" />
            <span asp-validation-for="PetInput.Breed" class="block text-sm ml-2 text-gray-900"></span>
        </div>
        <div class="form-group">
          <input asp-for="PetImage" class="form-control rounded-md appearance-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10" type="file">
        </div>
        <div class="form-group">
          <button type="submit" class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-md rounded-md text-white bg-indigo-500 hover:bg-indigo-600 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
            <span class="absolute left-0 inset-y-0 flex items-center pl-3">
              <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6" />
              </svg>
            </span>
            Add pet
          </button>
        </div>
      </form>
    </section>
  </div>
</div>

Petz.Web/Pages/App/Pets/Pet.cshtml
@page
@model PetModel
@{
    ViewData["Title"] = @Model.Pet.Name;
}

<section class="text-gray-600 body-font">
  <div class="container px-5 py-12 mx-auto">
    <div class="flex flex-wrap w-full justify-between">
        <div class="lg:w-1/2">
            <h1 class="sm:text-3xl text-2xl font-medium title-font mb-2 text-gray-900">@Model.Pet.Name</h1>
        </div>
        <div class="flex flex-row text-indigo-500 space-x-3">
            <a asp-area="" asp-page="/App/Pets/EditPet" asp-route-id="@Model.Pet.Id" title="Edit" class="hover:text-indigo-600">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-7 w-7" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
                </svg>
            </a>
            <a asp-area="" asp-page="/App/Pets/RemovePet" asp-route-id="@Model.Pet.Id" title="Remove" class="hover:text-indigo-600">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-7 w-7" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                </svg>
            </a>
        </div>
    </div>
    <p class="leading-relaxed text-base hover:text-gray-700 mb-10">@Model.Pet.Breed</p>
    <div class="mx-auto flex flex-wrap">    
        <img class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="/img/pets/@(Model.Pet.Id).jpg" alt=@Model.Pet.Name>
        <div class="lg:w-1/2 w-full lg:pl-10 mt-6 lg:mt-0">
            <div class="flex flex-wrap w-full mb-5 justify-between">
                <div class="lg:w-1/2 mb-6 lg:mb-0">
                    <h1 class="sm:text-3xl text-2xl font-medium title-font mb-2 text-gray-900">Tasks</h1>
                    <div class="h-1 w-20 bg-indigo-500 rounded"></div>
                </div>
                
                <a asp-area="" asp-page="/App/Tasks/AddTask" asp-route-id="@(Model.Pet.Id)">
                    <button class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-md">Add</button>
                </a>
            </div>

            @if (Model.UncompletedTasks.Count != 0)
            {
                <div class="flex flex-wrap sm:mx-auto -mx-2 mb-5">
                    @foreach (var task in Model.UncompletedTasks)
                    {
                        <div class="p-2 sm:w-1/2 w-full">
                            <div class="bg-gray-100 hover:bg-gray-200 rounded flex p-4 h-full items-center">
                                <div class="flex flex-col w-full">
                                    <div class="flex flex-row justify-between">
                                        <span class="text-indigo-600 title-font font-medium">@task.Title</span>
                                        <form asp-page-handler="complete" method="post">
                                            <input type="hidden" asp-for="TaskId" value=@task.Id />
                                            <input type="hidden" asp-for="Id" value="@Model.Pet.Id" />
                                            <button type="submit" title="Complete" class="hover:text-indigo-600 align-middle">
                                                <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" />
                                                </svg>
                                            </button>
                                        </form> 
                                    </div>
                                    <span class="text-md font-medium mb-2"><span class="text-indigo-600">Due: </span>@task.Date.ToString("HH:mm, dd MMM")</span>
                                    <span class="text-sm font-light">@task.Description</span>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            }
            else 
            {
                <div class="flex justify-center">
                    <p class="text-lg text-center text-gray-900 font-medium title-font mt-2 mb-5">No tasks have been added yet.</p>
                </div>
            }  
                     
            <div class="flex flex-wrap w-full mb-5 justify-between">
                <div class="lg:w-1/2 mb-6 lg:mb-0">
                    <h1 class="sm:text-3xl text-2xl font-medium title-font mb-2 text-gray-900">Health</h1>
                    <div class="h-1 w-20 bg-indigo-500 rounded"></div>
                </div>
                
                <a asp-area="" asp-page="/App/Records/AddMedicalRecord" asp-route-id="@(Model.Pet.Id)">
                    <button class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-md">Add</button>
                </a>
            </div>

            @if (Model.Pet.MedicalRecords.ToList().Count != 0)
            {
                <div class="flex flex-wrap sm:mx-auto -mx-2 mb-5">
                    @foreach (var medicalRecord in Model.Pet.MedicalRecords)
                    {
                        <div class="p-2 sm:w-1/2 w-full">
                            <div class="bg-gray-100 hover:bg-gray-200 rounded flex p-4 h-full items-center">
                                <div class="flex flex-col w-full">
                                    <div class="flex flex-row justify-between mb-2">
                                        <span class="text-indigo-600 title-font font-medium">@medicalRecord.Title</span>
                                        <a asp-area="" asp-page="/App/Records/RemoveMedicalRecord" asp-route-id=@medicalRecord.Id title="Remove" class="hover:text-indigo-600">
                                            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                                            </svg>
                                        </a>
                                    </div>
                                    <span class="text-sm font-light">@medicalRecord.Description</span>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            }
            else 
            {
                <div class="flex justify-center">
                    <p class="text-lg text-center text-gray-900 font-medium title-font mt-2 mb-5">No medical records have been added yet.</p>
                </div>
            }  

            <div class="flex flex-wrap w-full mb-5 justify-between">
                <div class="lg:w-1/2 mb-6 lg:mb-0">
                    <h1 class="sm:text-3xl text-2xl font-medium title-font mb-2 text-gray-900">Expenses</h1>
                    <div class="h-1 w-20 bg-indigo-500 rounded"></div>
                </div>
                
                <a asp-area="" asp-page="/App/Records/AddExpenseRecord" asp-route-id="@(Model.Pet.Id)">
                    <button class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-md">Add</button>
                </a>
            </div>

            @if (Model.Pet.ExpenseRecords.ToList().Count != 0)
            {
                <div class="flex flex-wrap sm:mx-auto -mx-2 mb-5 ">
                    @foreach (var expenseRecord in Model.Pet.ExpenseRecords)
                    {
                        <div class="p-2 sm:w-1/2 w-full">
                            <div class="bg-gray-100 hover:bg-gray-200 rounded flex p-4 h-full items-center">
                                <div class="flex flex-col w-full">
                                    <div class="flex flex-row justify-between">
                                        <span class="title-font font-medium text-indigo-600">@expenseRecord.Title</span>
                                        <a asp-area="" asp-page="/App/Records/RemoveExpenseRecord" asp-route-id=@expenseRecord.Id title="Remove" class="hover:text-indigo-600">
                                            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                                            </svg>
                                        </a>
                                    </div>
                                    <span class="text-md font-medium mb-2">@expenseRecord.Price Ft</span>
                                    <span class="text-sm font-light">@expenseRecord.Description</span>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            }
            else 
            {
                <div class="flex justify-center">
                    <p class="text-lg text-center text-gray-900 font-medium title-font mt-2 mb-5">No expense records have been added yet.</p>
                </div>
            }  

        </div>
    </div>
  </div>
</section>

Petz.Web/Pages/App/Pets/RemovePet.cshtml
@page
@model RemovePetModel
@{
    ViewData["Title"] = "Remove pet";
}

<div class="font-sans min-h-screen flex items-start justify-center py-12 px-4 sm:px-6 lg:px-8">
  <div class="max-w-md w-full space-y-8">
    <div>
        <img class="mx-auto h-12 w-auto" src="/img/logo.png" alt="Petz">
        <h2 class="mt-6 text-center text-3xl font-extrabold text-gray-900">
            Are you sure you want to remove <span class="text-indigo-500">@Model.CurrentPet.Name</span> from the @Model.CurrentPet.Family.Name family?
        </h2>
    </div>
    <section>
      <form method="post" class="mt-8 space-y-6">
        <div class="form-group">
          <button type="submit" class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-md rounded-md text-white bg-indigo-500 hover:bg-indigo-600 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
            <span class="absolute left-0 inset-y-0 flex items-center pl-3">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                </svg>
            </span>
            Remove pet
          </button>
        </div>
      </form>
    </section>
  </div>
</div>